---
- name: JCL Banner
  hosts: 127.0.0.1
  gather_facts: no
  roles:
    - jcl-banner
- name: Install VXLAN config to linux host
  hosts: nvhost
  gather_facts: no
  pre_tasks:
    - name: update host ip
      set_fact:
        ansible_ssh_host: "{{ PrivateAddressHostVM }}"
  roles:
    - load-vxlan-nv-host
