---
- name: Ixia ReST Calls to Test
  hosts: ixia
  gather_facts: no
  tasks:
    - name: Get IxNetwork session
      uri:
        url: http://{{ ansible_ssh_host }}:{{ rest_port }}/api/v1/sessions/
        method: GET
        status_code: 200
        return_content: yes
      register: json_response
      connection: local
      run_once: true

    - name: debug
      debug: msg={{ json_response }}
      run_once: true

    - name: Upload config file 
      shell: curl -X POST --data-binary "@ixia.ixncfg" -H "content-type:application/octet-stream" -H "content-disposition:attachment;filename=spirent" http://"{{ ansible_ssh_host }}":"{{ rest_port }}"/api/v1/sessions/1/ixnetwork/files?filename=ixia.ixncfg
      connection: local
      run_once: true

#    - name: Copy config file
#      win_copy: 
#        src: ixia.ixncfg
#        dest: c:\Users\jcluser\AppData\Local\sdnStreamManager\common\ixia.ixncfg
#      run_once: true
#      connection: local


    - name: load config file
      uri: 
        url: http://{{ ansible_ssh_host }}:{{ rest_port }}/api/v1/sessions/1/ixnetwork/operations/loadconfig
        method: POST
        headers:
          Content-Type: "application/json"
        body: 
          arg1:
             /api/v1/sessions/1/ixnetwork/files/ixia.ixncfg
        body_format: json
        status_code: 202
      register: response
      connection: local
      run_once: true

    - name: debug
      debug: msg={{ response }}
      run_once: true

#    - name: Copy config file
#      uri:
#        url: http://{{ ansible_ssh_host }}:{{ rest_port }}/api/v1/sessions/1/ixnetwork/operations/copyfile
#        method: POST
#        body: "windowsPathAndFileName='ixia.ixncfg'"
#        status_code: 201
#      register: response
#      connection: local
#      run_once: true
#      tags: 
#        - test
#    - name: debug
#      debug: msg={{ response }}
#      run_once: true
#      tags: 
#        - test
    - name: Pause
      pause:
        seconds: 80
      run_once: true

    - name: Assign Ports
      uri:
        url: http://{{ ansible_ssh_host }}:{{ rest_port }}/api/v1/sessions/1/ixnetwork/operations/assignports
        method: POST
        headers:
          Content-Type: "application/json"
        body:  "{{ rest_body }}"
        body_format: json
        status_code: 202
      register: response
      connection: local
      run_once: true

    - name: debug
      debug: msg={{ response }}
      run_once: true


