---
- name: Git push to JCL Git server
  hosts: 127.0.0.1
  connection: local
  tasks:
   - name: Create project on JCL Git Server
     uri:
       url: https://git.cloudlabs.juniper.net/api/v4/projects?private_token={{ api_access_token }}
       method: POST
       status_code: 201
       body: "visibility={{ visibility }}&default_branch=master&path={{ DirName }}"
       return_content: yes
       validate_certs: False
     register: json_response
     run_once: true

   - name: Get ssh url to created repo
     set_fact: git_repo="{{ (json_response.content | from_json ).ssh_url_to_repo }}"
     run_once: true

   - name: Debug
     debug: msg={{ git_repo }}
     run_once: true
  
   - command: git add .
   - command: git commit -m "Commit Snapshot"
     ignore_errors: yes
   - command: git push {{ git_repo }} master
 
