---
- name: check alt python version
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: check python version
      shell: /usr/bin/python3.9 --version
      register: python3_version
      ignore_errors: yes  # If not installed
      tags:
        - python-alt
    - debug: msg="{{ python3_version.stdout.split('\n') }}"
    - name: Install python if needed
      become: true
      block:
        - name: Print
          debug: msg="Python install needed"
        - name: Create directory for script
          shell: mkdir -p ~/ansible_local_python_install
        - name: copy shell install script
          copy: src=shell_scripts/install_python.sh dest=~/ansible_local_python_install mode=0777
        - name: copy shell dependency script
          copy: src=shell_scripts/install_dependencies.sh dest=~/ansible_local_python_install mode=0777
        - name: install dependency
          command: bash ~/ansible_local_python_install/install_dependencies.sh
#          become: True
        - name: install python
          command: sh ~/ansible_local_python_install/install_python.sh
      always:
        - name: clean-up
          shell: rm -f ~/ansible_local_python_install/install_*.sh
      when: python3_version.stderr | length != 0
      tags:
        - python-alt
