---
- name: docker test
  hosts: spirent
  tasks:
   - name: show container
     shell: docker ps -l -q
     become: true    
     register: result
     run_once: true
   - name: Set container id
     set_fact: 
       container_id: "{{ result.stdout }}"
     run_once: true
   - name: Copy xml file from container to lab server 
     shell: docker cp {{ container_id }}:/home/stcapi/savespirent.xml spirent.xml 
     become: true
     run_once: true
