---

- name: Check if dest directory is present
  file: path={{ config_dir }} state=directory
  run_once: true

- name: Install Junos OS package
  junos_install_os:
    host={{ junos_host }}
    reboot=yes
    version={{ os_version }}
    package=jinstall-ppc-14.1R4.10-domestic-signed.tgz
    port={{ netconf_port }}
    user={{ junos_username }}
    passwd={{ junos_passwd }}
    logfile=/tmp/ansible.changes.log
  register: sw
  notify: 
    - wait_reboot
   
