---
- name: list all vms
  virt:
    command: list_vms
  register: all_vms


- name: Start the vm if not running already 
  virt: 
    name: "{{ item }}"
    state: running
  with_items: "{{ all_vms.list_vms }}"
