---
# tasks file for jcl_banner
- name: Pause and Display Banner
  vars:
    msg: |
              /////////////////
                                     +-+-+-+-+-+-+-+ +-+-+-+-+-+ +-+-+-+-+
                                     |J|u|n|i|p|e|r| |C|l|o|u|d| |L|a|b|s|
                                     +-+-+-+-+-+-+-+ +-+-+-+-+-+ +-+-+-+-+
              /////////////////
              !!!!!!!!!!!!This is the older python2 only release of JCL Ansible Playbooks.!!!!!!!!!!!!!
              We have a NEW VERSION of JCL Ansible Playbooks which use python3 and ansible collections.
              python3 playbooks will not run in this mode.
              We encourage you to use the version of JCL Ansible Playbooks, run the following command
                                       -------------------
                                     / source switch.sh /
                                    -------------------
              in the playbook directory. It will replace the hosts file and change the environment variables.
  debug:
    msg: "{{ msg.split('\n') }}"
