---
- name: create spirent session
  connection: local
  uri:
    url: http://{{ ansible_ssh_host }}:{{ rest_port }}/stcapi/sessions
    method: POST
    HEADER_Content-Type: "application/x-www-form-urlencoded"
    body: "userid=Administrator&sessionname={{ spirent_session_name }}"
    return_content: yes
    status_code: 201
  run_once: true


