---
- name: Save config file
  uri:
    url: http://{{ ansible_ssh_host }}:{{ rest_port }}/api/v1/sessions/1/ixnetwork/operations/saveconfig
    method: POST
    headers:
      Content-Type: "application/json"
    body:
      arg1:
        /api/v1/sessions/1/ixnetwork/files/ixia.ixncfg
    body_format: json
    status_code: 202
  register: response
  connection: local
  run_once: true

- name: debug
  debug: msg={{ response }}
  run_once: true

- name: Download ixia config file
  get_url:
    url: http://{{ ansible_ssh_host }}:{{ rest_port }}/api/v1/sessions/1/ixnetwork/files/ixia.ixncfg
    dest: /root/JCL_Ansible_Playbooks/ixia.ixncfg
  register: response
  connection: local
  run_once: true


