---
- name: Checking NETCONF connectivity
  wait_for: host={{ junos_host }} port=830  timeout=5
- name: Pushing config
  junos_install_config: 
      host={{ junos_host }}
      port={{ netconf_port }}
      user={{ junos_username }}
      passwd={{ junos_passwd }}
      file={{ build_dir }}/{{ config_file }}
      overwrite=yes
      replace=no
      timeout=60
      logfile=/tmp/ansible.changes.log 
