---

- name: Check if source directory is present
  stat: path={{ config_templatized_dir }}/{{ config_file }}
  register: filestat
  
- name: Throw Error if file does not exist
  fail: msg="Error"
  when: filestat.stat.exists == False

- name: Build dest directory if it does not exist
  file: path={{ build_dir }} state=directory
  run_once: true
 
- name: Templating
  template: src={{ config_templatized_dir }}/{{ config_file }} dest={{ build_dir }}/{{ config_file }}
  when: filestat.stat.exists == True
  
