---
# tasks file for load-cyberflood-config
- name: Authenticate with CyberFlood
  uri:
    url: "{{ api_url }}token"
    method: POST
    force_basic_auth: yes
    user: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    status_code: 201
    validate_certs: no
    timeout: 20
  register: auth_ret
  connection: juniper.device.pyez
  run_once: true

- name: Upload test to cyberflood
  shell: "curl --location --request POST '{{ api_url }}tests/imports?type=avn' --header 'Accept: application/json' --header 'Content-Type: multipart/form-data' --header 'Authorization: Bearer {{ auth_ret.json.token }}' --form 'file=@{{ playbook_dir }}/{{ config_file }}' --insecure"
  connection: juniper.device.pyez
  run_once: true
